openapi: 3.0.1
info:
  title: API для управления коллекцией продуктов. Вариант 4197.
  description: API для управления коллекцией объектов класса `Product`. Второй сервис.
  version: 1.0.0
servers:
- url: https://se.ifmo.ru/~s333165/SOA/
  description: Королев Денис
- url: https://se.ifmo.ru/~s308414/SOA/
  description: Арсений Девяткин
paths:
  /ebay/filter/manufacturer/{manufacturerId}:
    get:
      summary: Получить все продукты по ID производителя
      tags: 
      - Дополнительные операции
      operationId: filterByManufacturer
      parameters:
      - name: manufacturerId
        in: path
        description: Идентификатор производителя
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Продукты успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
              - id: 1
                name: Product 1
                coordinates:
                  x: 10
                  "y": 20.5
                creationDate: 2023-10-01T12:00:00Z
                price: 500
                partNumber: A123
                manufactureCost: 1000
                unitOfMeasure: GRAMS
                owner:
                  name: John Doe
                  birthday: 1990-01-01T00:00:00Z
                  height: 180
                  passportID: "123456"
                  location:
                    x: 50.123
                    "y": 10.456
                    name: Moscow
        "400":
          description: Неверно указан ID производителя — должен быть положительным числом
          content:
            application/json:
              example:
                code: 400
                message: "Неверно указан ID производителя: должен быть положительным числом."
        "401":
          description: Отказ в доступе — требуется авторизация
          content:
            application/json:
              example:
                code: 401
                message: "Доступ запрещен: требуется авторизация."
        "403":
          description: Запрещено — у вас нет прав на доступ к этому ресурсу
          content:
            application/json:
              example:
                code: 403
                message: "Запрещено: у вас нет прав на доступ к этому ресурсу."
        "404":
          description: Продукты с указанным производителем не найдены
          content:
            application/json:
              example:
                code: 404
                message: Продукты с указанным производителем не найдены.
        "408":
          description: Время ожидания истекло — запрос не был обработан вовремя
          content:
            application/json:
              example:
                code: 408
                message: "Время ожидания истекло: запрос не был обработан вовремя."
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              example:
                code: 500
                message: Внутренняя ошибка сервера
        "503":
          description: Сервис временно недоступен — попробуйте позже
          content:
            application/json:
              example:
                code: 503
                message: "Сервис временно недоступен: попробуйте позже."
        "504":
          description: Ошибка шлюза — не удалось получить ответ от внешнего сервиса
          content:
            application/json:
              example:
                code: 504
                message: "Ошибка шлюза: не удалось получить ответ от внешнего сервиса."
  /ebay/price/decrease/{decreasePercent}:
    post:
      summary: Снизить цену на указанный процент
      tags: 
      - Дополнительные операции
      operationId: decreasePrice
      parameters:
      - name: decreasePercent
        in: path
        description: Процент уменьшения цены
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: float
      responses:
        "200":
          description: Цены успешно обновлены
          content:
            application/json:
               example:
                code: 200
                message: "Цены успешно обновлены."
        "400":
          description: Неверно указан процент уменьшения — процент должен быть положительным числом
          content:
            application/json:
              example:
                code: 400
                message: "Неверно указан процент уменьшения: процент должен быть положительным числом."
        "401":
          description: Отказ в доступе — требуется авторизация
          content:
            application/json:
              example:
                code: 401
                message: "Доступ запрещен: требуется авторизация."
        "403":
          description: Запрещено — у вас нет прав на доступ к этому ресурсу
          content:
            application/json:
              example:
                code: 403
                message: "Запрещено: у вас нет прав на доступ к этому ресурсу."
        "404":
          description: Продукты для снижения цены не найдены
          content:
            application/json:
              example:
                code: 404
                message: Продукты для снижения цены не найдены.
        "409":
          description: "Конфликт — не удается снизить цену, так как продукт не может быть уценен"
          content:
            application/json:
              example:
                code: 409
                message: "Конфликт: не удается снизить цену, так как продукт не может быть уценен."
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              example:
                code: 500
                message: Внутренняя ошибка сервера.
        "503":
          description: Сервис временно недоступен — попробуйте позже
          content:
            application/json:
              example:
                code: 503
                message: "Сервис временно недоступен: попробуйте позже."
        "504":
          description: Ошибка шлюза — не удалось получить ответ от внешнего сервиса
          content:
            application/json:
              example:
                code: 504
                message: "Ошибка шлюза: не удалось получить ответ от внешнего сервиса."
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          nullable: false
          readOnly: true # To indicate that this field should be auto-generated
          description: "Unique identifier for the resource, auto-generated by the server and must be > 0."
        name:
          type: string
          nullable: false
          minLength: 1
          description: "The name of the product. Must not be null or an empty string."
        coordinates:
          $ref: '#/components/schemas/Coordinates'
          nullable: false # Coordinates field cannot be null
        creationDate:
          type: string
          format: date-time
          nullable: false
          readOnly: true # To indicate that this field should be auto-generated
        price:
          type: integer
          nullable: true
          minimum: 1
          description: "The price of the product. If provided, it must be greater than 0."
        partNumber:
          type: string
          nullable: false
          uniqueItems: true
          description: "Unique part number of the product. Must not be null."
        manufactureCost:
          type: integer
          nullable: true
          description: "The manufacturing cost of the product."
        unitOfMeasure:
          $ref: '#/components/schemas/UnitOfMeasure'
        owner:
          $ref: '#/components/schemas/Person'

    Coordinates:
      type: object
      nullable: false
      properties:
        x:
          type: number
          minimum: -861
          description: "X coordinate of the location, must be greater than -861."
        y:
          type: number
          nullable: false
          minimum: -840
          description: "Y coordinate of the location, must be greater than -840 and non-null."

    Person:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
          description: "Name of the person. Must not be null or blank."
        birthday:
          type: string
          format: date-time
          nullable: false
          description: "Birthday of the person. Must not be null."
        height:
          type: integer
          nullable: true
          minimum: 1
          description: "Height of the person. If provided, it must be greater than 0."
        passportID:
          type: string
          nullable: true
          minLength: 1
          description: "Passport ID of the person. If provided, must not be an empty string."
        location:
          $ref: '#/components/schemas/Location'
          nullable: true # Location can be null

    Location:
      type: object
      properties:
        x:
          type: number
          description: "X coordinate of the location."
        y:
          type: number
          description: "Y coordinate of the location."
        name:
          type: string
          nullable: false
          maxLength: 444
          description: "Name of the location. Must not be null and must not exceed 444 characters."

    UnitOfMeasure:
      nullable: false
      type: string
      enum:
        - METERS
        - CENTIMETERS
        - MILLILITERS
        - GRAMS
